AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - "lib/tasks/**/*.rake"
    - "Rakefile"
    - "memory_bank_rails.gemspec"

Layout/LineLength:
  Max: 120
  Exclude:
    - "lib/generators/**"

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "lib/generators/**"

Metrics/AbcSize:
  Max: 26
  Exclude:
    - "lib/generators/**"

Metrics/ClassLength:
  Max: 120
  Exclude:
    - "lib/generators/**"
